[package]
name    = "protocol"
version = "0.1.0"
edition = "2021"
rust-version = "1.82"

[lib]
name = "protocol"
path = "src/lib.rs"

[dependencies]
serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
serde_json = { workspace = true }
