name: CI

on: [push, pull_request]

jobs:
  ci:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --workspace -- -D warnings
      - run: cargo test --workspace
